#!/bin/bash

# This script is executed while the application is stopped
# Activate VirtualEnv in order to use the correct libraries

echo "--> ACTION HOOK: build <--"

source "$OPENSHIFT_REPO_DIR.openshift/lib/utils"

echo "Setup path to include the custom Node.js version."
_SHOW_SETUP_PATH_MESSAGES="true" setup_path_for_custom_node_version

echo "Executing makefile production build"
cd "$OPENSHIFT_REPO_DIR"
HOME=`pwd` # hack, fixes error about insufficient priviledges when running npm
env PRODUCTION=1 make
