#!/bin/bash

# This script is executed while the application is stopped

echo "--> ACTION HOOK: pre_build <--"

source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"

echo "Executing Node.js install scripts"
ensure_node_is_installed

echo "Export commit hash to DEPLOYED_GIT_COMMIT_HASH for versioning static files"
cat ${OPENSHIFT_HOMEDIR}git/${OPENSHIFT_APP_NAME}.git/refs/heads/${OPENSHIFT_DEPLOYMENT_BRANCH} \
    > ${OPENSHIFT_HOMEDIR}.env/user_vars/DEPLOYED_GIT_COMMIT_HASH
