language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install --requirement requirements.txt --upgrade"
  - "npm install"
script:
  - "make lint test"

addons:
  sauce_connect: true
env:
  global:
    - secure: P9oBHBePwRduFw/lJpUAQwDQL8hpfbpqdHi5QeVzqNCzs7VYJ+EdbXBGFJ9ZvRiryKXAnIA3la/LitY/rjUIxgEPMF3vTYEjRPv6JLDsDQf4daxU3d/NAxJL1mjPFY/DdBC1yeGjyi7JcfGsrunjQtRWhPfXCm3q/saCVJphcr0=
    - secure: b0eCVMA6OT0m4T/MthVihXARXy6dYLAOB7/WMR8zmTRQzjvFa5s81qSjFYCDdzCm6acVMdoT71IqkrRMQiCraLcicuLBC5P5sWyeKbHZTS7o6aD1OGkiYQ3sZ4xU2NL8FTH6UOyeIHororvR5KZJZFooKVFIocQKrxA9qWjxaX0=

notifications:
  email: false

deploy:
  provider: openshift
  user: lochlan.mcintosh@gmail.com
  password:
    secure: lWbggpFeqRrDdzd5GatMy3mUnDsK0fyALhFV2DbH6g3HHUpNa4OhOADJEkUu+6ahU1KAMksZ/GxZ835hVAMuMD/6g5RK/LyDQDNr/KFERP3QPZG69NW5EmUsCtvkAdK8tPeHtmTfTZmgmizTGaJoTrvunarVxJ5LItM8HO8kZA4=
  app: lochlanmcintoshcom
  domain: lochlan
  on:
    repo: Lochlan/LochlanMcIntosh.com
    python: "3.3"