language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install --requirement requirements.txt --upgrade"
  - "nvm install 0.10"
  - "npm install"
script:
  - "make test"

notifications:
  email: false
