language: python
python:
- '3.3'
install:
- pip install --requirement requirements.txt --upgrade
- nvm install v6.4.0
- npm install npm@3.0.0 -g
- npm install
script:
- make test
addons:
  sauce_connect: true
env:
  global:
  - secure: P9oBHBePwRduFw/lJpUAQwDQL8hpfbpqdHi5QeVzqNCzs7VYJ+EdbXBGFJ9ZvRiryKXAnIA3la/LitY/rjUIxgEPMF3vTYEjRPv6JLDsDQf4daxU3d/NAxJL1mjPFY/DdBC1yeGjyi7JcfGsrunjQtRWhPfXCm3q/saCVJphcr0=
  - secure: b0eCVMA6OT0m4T/MthVihXARXy6dYLAOB7/WMR8zmTRQzjvFa5s81qSjFYCDdzCm6acVMdoT71IqkrRMQiCraLcicuLBC5P5sWyeKbHZTS7o6aD1OGkiYQ3sZ4xU2NL8FTH6UOyeIHororvR5KZJZFooKVFIocQKrxA9qWjxaX0=
  - secure: E5OrlKtUVuKk5C612TsSmWLwpRyVuukJ6JHLJmsw+yecIkmhW7dCmzfc5LVoLm5GO1WX8nDwGeymDDjXU2rIlBH7jK3wo0Pgn60U9iwA99nJf4Le4eNvqy2M3s2MnvR/byilSyofV2LbpSO4SrQhj3V4Y23wo54JlwPn+WaPto0=
  - secure: XnCvK+w/lDF/EjGWb2CJyp/XiyugI2yPZvit1i7MCBhbJU3tL28wzt9lzS0nhuOFqfGdPtBLx1hFWoXTTyF0myBV4SWVlS9Eiu+WoH4cCTwgQNx5zHURqszESuCbW04rfG8x9VN0vhsIOgcnX/kNU71CqpSqLpN4+p1x6b5Xx0k=
notifications:
  email: false
  slack:
    secure: rTIZQcotXWytY0Xxg6HaqELxV7JVOS7aXyieVKCpgsGokBlxR+kVhjddVzNTbsHVgc8wSNBsp2nAwH645i1YJBEHAucJqg3Wkppg6efsozztILAa8GqWtXm411NUecq5gCrHcRa+Tbwl1O+2vD5sy0b+crsHrWR1EYk9xMSGPq0=
deploy:
  provider: openshift
  user: lochlan.mcintosh@gmail.com
  password:
    secure: "$OPENSHIFT_PASSWORD"
  app: lochlanmcintoshcom
  domain: lochlan
  on:
    repo: Lochlan/LochlanMcIntosh.com
    python: '3.3'
